# Generated by Django 2.2.3 on 2019-11-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0012_auto_20191120_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Стихия'),
        ),
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.ManyToManyField(to='pokemon_entities.Pokemon')),
            ],
        ),
    ]
