# Generated by Django 2.2.3 on 2019-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0013_auto_20191120_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='pokemon',
            field=models.ManyToManyField(to='pokemon_entities.Pokemon'),
        ),
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='title',
        ),
        migrations.AddField(
            model_name='pokemonelementtype',
            name='title',
            field=models.CharField(default='', max_length=20),
        ),
    ]
