# Generated by Django 2.2.3 on 2019-11-22 11:36

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0017_auto_20191121_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonelementtype',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/home/yoj/devman/pokemon_map/media'), upload_to='', verbose_name='Изображение'),
        ),
    ]
