# Generated by Django 2.2.3 on 2019-11-22 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0019_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonelementtype',
            name='strong_against',
        ),
    ]
