# Generated by Django 2.2.3 on 2019-11-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0021_pokemonelementtype_strong_against'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonelementtype',
            name='strong_against',
            field=models.ManyToManyField(blank=True, null=True, related_name='string_against', to='pokemon_entities.PokemonElementType'),
        ),
    ]
