# Generated by Django 2.2.3 on 2019-11-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0023_auto_20191122_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(related_name='element_types', to='pokemon_entities.PokemonElementType', verbose_name='Стихия'),
        ),
    ]
