# Generated by Django 2.2.3 on 2019-11-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0024_auto_20191126_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='next_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prev_pokemons', to='pokemon_entities.Pokemon', verbose_name='В кого эволюционирует'),
        ),
    ]
