# Generated by Django 2.2.3 on 2019-11-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0025_auto_20191126_0757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='Stamina',
            new_name='stamina',
        ),
    ]
